// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lestrrat-go/file-rotatelogs"
	"go-scaffold/internal/app"
	"go-scaffold/internal/app/command"
	greet3 "go-scaffold/internal/app/command/handler/greet"
	"go-scaffold/internal/app/command/script"
	"go-scaffold/internal/app/component/casbin"
	"go-scaffold/internal/app/component/orm"
	"go-scaffold/internal/app/component/redis"
	"go-scaffold/internal/app/component/trace"
	"go-scaffold/internal/app/config"
	"go-scaffold/internal/app/cron"
	"go-scaffold/internal/app/cron/job"
	"go-scaffold/internal/app/http"
	greet2 "go-scaffold/internal/app/http/handler/v1/greet"
	trace2 "go-scaffold/internal/app/http/handler/v1/trace"
	user3 "go-scaffold/internal/app/http/handler/v1/user"
	"go-scaffold/internal/app/http/router"
	"go-scaffold/internal/app/repository/user"
	"go-scaffold/internal/app/service/greet"
	user2 "go-scaffold/internal/app/service/user"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(rotateLogs *rotatelogs.RotateLogs, zapLogger *zap.Logger, configConfig *config.Config) (*app.App, func(), error) {
	ormConfig := configConfig.DB
	db, cleanup2, err := orm.New(ormConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	traceConfig := configConfig.Trace
	tracer, cleanup3, err := trace.New(traceConfig, zapLogger)
	if err != nil {
		cleanup2()
		return nil, nil, err
	}
	redisConfig := configConfig.Redis
	client, cleanup4, err := redis.New(redisConfig, zapLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		return nil, nil, err
	}
	example := job.NewExample(zapLogger)
	cronCron, err := cron.New(zapLogger, db, client, example)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		return nil, nil, err
	}
	configHTTP := configConfig.HTTP
	configApp := configConfig.App
	jwt := configConfig.JWT
	casbinConfig := configConfig.Casbin
	enforcer, err := casbin.New(casbinConfig, db)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		return nil, nil, err
	}
	service := greet.NewService(zapLogger)
	handler := greet2.NewHandler(zapLogger, service)
	traceHandler := trace2.NewHandler(zapLogger, configConfig, tracer)
	repository := user.NewRepository(db, client)
	userService := user2.NewService(zapLogger, repository)
	userHandler := user3.NewHandler(zapLogger, userService)
	engine := router.New(rotateLogs, zapLogger, configApp, configHTTP, jwt, enforcer, handler, traceHandler, userHandler)
	server := http.NewServer(zapLogger, configHTTP, engine)
	appApp := app.New(zapLogger, db, tracer, cronCron, server, enforcer)
	return appApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
	}, nil
}

func initCommand(rotateLogs *rotatelogs.RotateLogs, zapLogger *zap.Logger, configConfig *config.Config) (*command.Command, func(), error) {
	handler := greet3.NewHandler(zapLogger)
	s0000000000 := script.NewS0000000000(zapLogger)
	commandCommand := command.New(handler, s0000000000)
	return commandCommand, func() {
	}, nil
}
