// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package queries

import (
	"gorm.io/cli/gorm/field"
)

var Product = struct {
	ID        field.Number[int64]
	CreatedAt field.Number[int64]
	UpdatedAt field.Number[int64]
	DeletedAt field.Number[int64]
	Name      field.String
	Desc      field.String
	Price     field.Number[int]
}{
	ID:        field.Number[int64]{}.WithColumn("id"),
	CreatedAt: field.Number[int64]{}.WithColumn("created_at"),
	UpdatedAt: field.Number[int64]{}.WithColumn("updated_at"),
	DeletedAt: field.Number[int64]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	Desc:      field.String{}.WithColumn("desc"),
	Price:     field.Number[int]{}.WithColumn("price"),
}
