// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package queries

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	ID        field.Number[int64]
	CreatedAt field.Number[int64]
	UpdatedAt field.Number[int64]
	DeletedAt field.Number[int64]
	Username  field.String
	Password  field.String
	Nickname  field.String
	Phone     field.String
	Salt      field.String
}{
	ID:        field.Number[int64]{}.WithColumn("id"),
	CreatedAt: field.Number[int64]{}.WithColumn("created_at"),
	UpdatedAt: field.Number[int64]{}.WithColumn("updated_at"),
	DeletedAt: field.Number[int64]{}.WithColumn("deleted_at"),
	Username:  field.String{}.WithColumn("username"),
	Password:  field.String{}.WithColumn("password"),
	Nickname:  field.String{}.WithColumn("nickname"),
	Phone:     field.String{}.WithColumn("phone"),
	Salt:      field.String{}.WithColumn("salt"),
}
