version: "3"

services:

  #################### app ####################
  app:
    image: ${APP_IMAGE}
    networks:
      go-scaffold:
        aliases:
          - app
    ports:
      - "${APP_PORT}:9527"
    command:
      - "./dockerize"
      - "-wait"
      - "tcp://mysql:3306"
      - "./bin/app"
      - "server"
    volumes:
      - "./dockerize:/app/dockerize"
      - "${APP_CONFIG_PATH}:/app/etc/config.yaml"
    depends_on:
      - mysql
      - redis
    restart: always
  #################### app ####################

  #################### mysql ####################
  mysql:
    image: mysql:${MYSQL_TAG}
    networks:
      go-scaffold:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-scaffold
    ports:
      - "${MYSQL_PORT}:3306"
    command: >
      bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"
    volumes:
      - "./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./mysql/data:/var/lib/mysql"
      - "./apollo/migrate:/docker-entrypoint-initdb.d"
  #################### mysql ####################

  #################### postgres ####################
  postgres:
    image: postgres:${POSTGRES_TAG}
    networks:
      go-scaffold:
        aliases:
          - postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go-scaffold
    ports:
      - "${POSTGRES_PORT}:5432"
    command: >
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - "./postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgres/data/:/var/lib/postgresql"
      - "./postgres/initdb.d/:/docker-entrypoint-initdb.d/"
  #################### postgres ####################

  #################### redis ####################
  redis:
    image: redislabs/redismod:${REDIS_TAG}
    networks:
      go-scaffold:
        aliases:
          - redis
    ports:
      - "${REDIS_PORT}:6379"
    entrypoint:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/data:/data/"

  redis-insight:
    image: redislabs/redisinsight:${REDIS_INSIGHT_TAG}
    networks:
      go-scaffold:
        aliases:
          - redis-insight
    restart: always
    ports:
      - "${REDIS_INSIGHT_PORT}:8001"
    volumes:
      - "./redisinsight/data/:/db/"
  #################### redis ####################

  #################### jaeger ####################
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_TAG}
    networks:
      go-scaffold:
        aliases:
          - jaeger
    environment:
      SPAN_STORAGE_TYPE: "badger"
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: "/badger/data"
      BADGER_DIRECTORY_KEY: "/badger/key"
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "${JAEGER_SERVE_CONFIGS_PORT}:5778"       # serve configs port
      - "${JAEGER_SERVE_FRONTEND_PORT}:16686"     # serve UI port
      - "${JAEGER_OTLP_GRPC_PORT}:4317"           # OTLP gRPC port
      - "${JAEGER_OTLP_HTTP_PORT}:4318"           # OTLP HTTP port
    volumes:
      - "./jaeger/data:/badger"
  #################### jaeger ####################

  #################### apollo ####################
  apollo-configservice:
    image: apolloconfig/apollo-configservice:${APOLLO_CONFIG_SERVICE_TAG}
    networks:
      go-scaffold:
        aliases:
          - apollo-configservice
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      EUREKA_INSTANCE_HOME_PAGE_URL: "http://apollo-configservice:8080"
    ports:
      - "${APOLLO_CONFIG_SERVICE_PORT}:8080"

  apollo-adminservice:
    image: apolloconfig/apollo-adminservice:${APOLLO_ADMIN_SERVICE_TAG}
    networks:
      go-scaffold:
        aliases:
          - apollo-adminservice
    depends_on:
      - mysql
      - apollo-configservice
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      EUREKA_INSTANCE_HOME_PAGE_URL: "http://apollo-adminservice:8090"
    ports:
      - "${APOLLO_ADMIN_SERVICE_PORT}:8090"

  apollo-portal:
    image: apolloconfig/apollo-portal:${APOLLO_PORTAL_SERVICE_TAG}
    networks:
      go-scaffold:
        aliases:
          - apollo-portal
    depends_on:
      - mysql
      - apollo-configservice
      - apollo-adminservice
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      APOLLO_PORTAL_ENVS: "dev"
      DEV_META: "http://apollo-configservice:8080"
    ports:
      - "${APOLLO_PORTAL_SERVICE_PORT}:8070"
  #################### apollo ####################

  #################### etcd ####################
  etcd:
    image: bitnami/etcd:${ETCD_TAG}
    networks:
      go-scaffold:
        aliases:
          - etcd
    restart: always
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "${ETCD_PORT}:2379"
      - "${ETCD_ADVERTISED_PORT}:2380"
    volumes:
      - "./etcd/conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml"
  #################### etcd ####################

  #################### kafka ####################
  kafka-1:
    image: 'bitnami/kafka:${KAFKA_TAG}'
    networks:
      go-scaffold:
        aliases:
          - kafka-1
    user: "root"
    ports:
      - '${KAFKA_1_PORT}:${KAFKA_1_PORT}'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=avyt1wlZRqyXwQ4JupT7Aw
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:${KAFKA_1_PORT},CONTROLLER://kafka-1:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_1_ADVERTISED_LISTENERS}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./kafka/broker-1/data:/bitnami/kafka"

  kafka-2:
    image: 'bitnami/kafka:${KAFKA_TAG}'
    networks:
      go-scaffold:
        aliases:
          - kafka-2
    user: "root"
    ports:
      - '${KAFKA_2_PORT}:${KAFKA_2_PORT}'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=avyt1wlZRqyXwQ4JupT7Aw
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:${KAFKA_2_PORT},CONTROLLER://kafka-2:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_2_ADVERTISED_LISTENERS}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./kafka/broker-2/data:/bitnami/kafka"
  #################### kafka ####################

networks:
  go-scaffold: