name: app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file : 'go.mod'

      - name: Setup Go Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Run Unit Test
        run: |
          task download
          task proto
          task generate
          task test

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Run semantic-release
        if: github.repository == 'OldSmokeGun/go-scaffold' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}